### ISSUE TITLE
Spanish characters do not work

### ISSUE THREAD

**Issue by manwy** [linuxserver/docker-libreoffice#2]
When I type characters like "ñ" or "á" they don't appear in LibreOffice. Is there a way to fix this and make them appear?

**Environment**

**OS**: Raspbian buster. arm32
**Command used to create docker containe**r (docker-compose):
```
version: "2.1"

services:
   libreoffice:
      image: linuxserver/libreoffice
      container_name: libreoffice
      restart: always
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Madrid
      networks:
         - web
      volumes:
         - $PWD/config:/config
      labels:
         - "traefik.enable=true"
         - "traefik.backend=libreoffice"
         - "traefik.frontend.rule=Host:office.XXXXX.duckdns.org"
         - "traefik.docker.network=web"
         - "traefik.port=3000"
networks:
   web:
      external: true
```
